<?xml version="1.0" encoding="UTF-8"?>
<bean:beans xmlns="http://www.springframework.org/schema/batch"
	xmlns:bean="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:p="http://www.springframework.org/schema/p" xmlns:tx="http://www.springframework.org/schema/tx"
	xmlns:aop="http://www.springframework.org/schema/aop" xmlns:context="http://www.springframework.org/schema/context"
	xsi:schemaLocation="http://www.springframework.org/schema/beans 
    http://www.springframework.org/schema/beans/spring-beans-3.0.xsd  
    http://www.springframework.org/schema/tx 
    http://www.springframework.org/schema/tx/spring-tx-3.0.xsd  
    http://www.springframework.org/schema/aop 
    http://www.springframework.org/schema/aop/spring-aop-3.0.xsd  
    http://www.springframework.org/schema/context 
    http://www.springframework.org/schema/context/spring-context-2.5.xsd
    http://www.springframework.org/schema/batch 
    http://www.springframework.org/schema/batch/spring-batch-2.2.xsd">
	<bean:import resource="classpath:job-context.xml" />

	<job id="retryJob">
		<step id="retryStep">
			<tasklet>
				<!-- 重试5次 -->
				<chunk reader="reader" processor="alwaysExceptionProcessor" writer="writer"
					commit-interval="1" retry-limit="5">
					<!-- 重试监听 -->
					<retry-listeners>
						<listener ref="systemRetryListener"/>
					</retry-listeners>
					<!-- 发生RuntimeException异常时，进行重试；FileNotFoundException不进行重试 -->
					<retryable-exception-classes>
						<include class="java.lang.RuntimeException"/>
						<exclude class="java.io.FileNotFoundException"/>
					</retryable-exception-classes>
				</chunk>
			</tasklet>
		</step>
	</job>


   <job id="retryPolicyJob">
        <step id="retryPolicyStep">
          <tasklet>
          	<!-- 使用重试策略-->
				<chunk reader="reader" processor="alwaysExceptionProcessor" writer="writer" 
				    commit-interval="1" retry-policy="exceptionClassifierRetryPolicy">
         		</chunk>
		  </tasklet>
        </step>
    </job>
    
    <!-- 自定义重试策略，当MockARuntimeException异常重试3次，MockBRuntimeException异常重试5次，只要一个达到重试次数就失败  -->
    <bean:bean id="exceptionClassifierRetryPolicy" class="org.springframework.retry.policy.ExceptionClassifierRetryPolicy">
    	<bean:property name="policyMap">
    		<bean:map>
    			<bean:entry key="fun.deepsky.batch.robust.retry.MockARuntimeException">
    				<bean:bean class="org.springframework.retry.policy.SimpleRetryPolicy">
    					<bean:property name="maxAttempts" value="3"/>
    				</bean:bean>
    			</bean:entry>
      			<bean:entry key="fun.deepsky.batch.robust.retry.MockBRuntimeException">
    				<bean:bean class="org.springframework.retry.policy.SimpleRetryPolicy">
    					<bean:property name="maxAttempts" value="5"/>
    				</bean:bean>
    			</bean:entry>  		
    		</bean:map>
    	</bean:property>
    </bean:bean>
    
    
	<bean:bean id="systemRetryListener" class="fun.deepsky.batch.robust.retry.SystemRetryListener">
	</bean:bean>

	<bean:bean id="reader"
		class="fun.deepsky.batch.robust.retry.AutoReader">
		<bean:property name="maxCount" value="100" />
	</bean:bean>

	<bean:bean id="writer" class="fun.deepsky.batch.robust.skip.ConsoleWriter" />

	<bean:bean id="radomExceptionItemProcessor" 
	    class="fun.deepsky.batch.robust.retry.RadomExceptionItemProcessor" />
	    
	<bean:bean id="alwaysExceptionProcessor"
		class="fun.deepsky.batch.robust.retry.AlwaysExceptionItemProcessor" />

</bean:beans>